In [64]:
#Sample Code:

import numpy as np
from datetime import datetime
a = np.array([10,20,30])
b = np.array([1,2,3])
print(type(a))

#dot product: 10x1+20x2+30x3=140


#Traditional Python code to find dot product
def dot_product(a,b):
    result = 0
    for m,n in zip(a,b):
        result += m*n
    return result
    
before = datetime.now()
for i in range(1000000):
    dot_product(a,b)
after=datetime.now()
print("The time taken:",after-before)

# Numpy Library code to find dot product
before = datetime.now()
for i in range(1000000):
    np.dot(a,b)
after=datetime.now()
print("The time taken:",after-before)

<class 'numpy.ndarray'>
The time taken: 0:00:04.935001
The time taken: 0:00:03.158807


In [80]:
import array
a = array.array('i',[10,20,30]) # i represents int type array
import math  # for understanding array.array like math.math
x = math.sqrt(4)
print(type(a))
print(a)
print("Element by element:")
for i in range(len(a)):
    print(a[i])

<class 'array.array'>
array('i', [10, 20, 30])
Element by element:
10
20
30


In [82]:
import numpy
a = numpy.array([10,20,30])
print(type(a))
print(a)
print("Element one by one")
for x in a:
    print(x)

<class 'numpy.ndarray'>
[10 20 30]
Element one by one
10
20
30


In [96]:
import  numpy as np
a = np.array([10,20,30])
print(a)
print(a+1)
print(a*2)
print(a/2)
l=[10,20,30]
print(l)
#print(l+1) can only concatenate list (not "int") to list

[10 20 30]
[11 21 31]
[20 40 60]
[ 5. 10. 15.]
[10, 20, 30]


In [100]:
import numpy
import sys
a = numpy.array([10,20,30,40,50,60,70,10,20,30,40,50,60,])
l=[10,20,30,40,50,60,70,10,20,30,40,50,60,]
print("The size of numpy array:",sys.getsizeof(a))
print("The size of list", sys.getsizeof(l))

The size of numpy array: 216
The size of list 168
