In [5]:
import numpy as np
a = np.array([10,20,30,40])
a.ndim

1

In [7]:
a.shape

(4,)

In [9]:
a.size


4

In [11]:
a.dtype

dtype('int64')

In [13]:
a.itemsize

8

In [15]:
a=np.array([[10,20,30],[40,50,60]],dtype=float)

In [19]:
a


array([[10., 20., 30.],
       [40., 50., 60.]])

In [21]:
a.shape

(2, 3)

In [23]:
a.size

6

In [25]:
a.dtype

dtype('float64')

In [27]:
a.itemsize

8

In [29]:
a.ndim

2

In [35]:
a=np.array([10,20,30,40])
import sys
sys.getsizeof(a)

144

In [37]:
a.dtype

dtype('int64')

In [39]:
a=np.array([10.5,19.2])
a.dtype

dtype('float64')

In [41]:
a=np.array([10,20,30,40,50],dtype='i8')

In [43]:
a.dtype

dtype('int64')

In [45]:
a=np.array([10,20,30,40,50],dtype='int8')

In [47]:
a.dtype

dtype('int8')

In [49]:
a=np.array([10,20,30,40,50],dtype='i')

In [51]:
a.dtype

dtype('int32')

In [55]:
a=np.array(['a',10,10.5],dtype=int) #Invalid literal for int() with base 10: 'a'

ValueError: invalid literal for int() with base 10: 'a'

In [57]:
a=np.array([10,20,30])
a.dtype

dtype('int64')

In [59]:
b=a.astype('float64')

In [61]:
b

array([10., 20., 30.])

In [63]:
print(b)

[10. 20. 30.]


In [65]:
print(a)

[10 20 30]


In [67]:
type(b)

numpy.ndarray

In [69]:
b.dtype

dtype('float64')

In [71]:
a.dtype

dtype('int64')

In [73]:
c=float64(b)

NameError: name 'float64' is not defined

In [75]:
c=np.float64(b)

In [77]:
c.dtype

dtype('float64')

In [79]:
type(c)

numpy.ndarray

In [81]:
x=np.boolean(a)

AttributeError: module 'numpy' has no attribute 'boolean'

In [83]:
x=np.bool(a)

In [85]:
print(x)

[ True  True  True]


In [87]:
x.dtype

dtype('bool')

In [89]:
type(x)

numpy.ndarray

In [91]:
#slicing in NumPY


In [95]:
l=[10,20,30,40,50,60,70]
l[2:5]


[30, 40, 50, 60, 70]

In [97]:
l[2:]

[30, 40, 50, 60, 70]

In [99]:
l[:5]

[10, 20, 30, 40, 50]

In [101]:
l[:]

[10, 20, 30, 40, 50, 60, 70]

In [113]:
l[0:7:4]

[10, 50]

In [115]:
l

[10, 20, 30, 40, 50, 60, 70]

In [117]:
l[-7]

10

In [119]:
l[-1]

70

In [139]:
l
l
l

[10, 20, 30, 40, 50, 60, 70]

In [141]:
print(l)

[10, 20, 30, 40, 50, 60, 70]


In [143]:
print(l,type(l))

[10, 20, 30, 40, 50, 60, 70] <class 'list'>


In [151]:
l[::4]

[10, 50]

In [153]:
l[1:7:-1]

[]

In [155]:
l[5:1:-1]

[60, 50, 40, 30]

In [167]:
l[7:1:-1]

[70, 60, 50, 40, 30]

In [169]:
a=np.array([10,20,30,40,50,60,70])
a

array([10, 20, 30, 40, 50, 60, 70])

In [171]:
a[2:6]

array([30, 40, 50, 60])

In [173]:
a[:6]

array([10, 20, 30, 40, 50, 60])

In [175]:
a[0:]

array([10, 20, 30, 40, 50, 60, 70])

In [177]:
a[:]

array([10, 20, 30, 40, 50, 60, 70])

In [179]:
a[2:6:1]

array([30, 40, 50, 60])

In [181]:
a[2:6:3]

array([30, 60])

In [183]:
a[5:1:-1]

array([60, 50, 40, 30])

In [185]:
a[5:1:-2]

array([60, 40])

In [187]:
a[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [189]:
a[::-2]

array([70, 50, 30, 10])

In [191]:
a[2:0:1]

array([], dtype=int64)

In [193]:
a[-7:-1]

array([10, 20, 30, 40, 50, 60])

In [195]:
a=np.array([[10,20],[30,40],[50,60]])

In [197]:
a.shape

(3, 2)

In [199]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [201]:
a[:,0:1]

array([[10],
       [30],
       [50]])

In [227]:
a[1:2,0:2]

array([[30, 40]])

In [229]:
a[0:2,0:2]

array([[10, 20],
       [30, 40]])

In [251]:
a[0:3:2,0:2]

array([[10, 20],
       [50, 60]])

In [253]:
a[::2,:]

array([[10, 20],
       [50, 60]])

In [5]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
indexes=np.array([0,2,7])
a[indexes]

array([10, 30, 80])

In [20]:
l=[0,2,7]
a[l]
a[[0,2,7]]

array([10, 30, 80])

In [22]:
a[[0,2,7,0,0,2,2,7,7]]

array([10, 30, 80, 10, 10, 30, 30, 80, 80])

In [24]:
a[[0,2,7]]

array([10, 30, 80])

In [26]:
l=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a=np.array(l)

In [30]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
print(a[[0,1,2,3],[0,1,2,3]])

[ 1  6 11 16]


In [38]:
a[[1,3],[0,2]]

array([ 5, 15])

In [44]:
a[[1,0],[2,3]]

array([7, 4])

In [46]:
a.shape

(4, 4)

In [50]:
a.itemsize

8

In [52]:
a.dtype

dtype('int64')

In [54]:
a.dtype

dtype('int64')

In [56]:
a.size

16

In [70]:
print(73//2)
print(73/2)
print(73%2)
print(73+2)
print(73-2)
print(73*2)
print(73**2)
print(73.0//2)
print(73//2.0)

36
36.5
1
75
71
146
5329
36.0
36.0


In [72]:
import numpy as np
a=np.array([10,20,30,40,50])

In [90]:
a=np.array([10,20,30,40,50])
a+2

array([12, 22, 32, 42, 52])

In [92]:
a=np.array([10,20,30,40,50])
a*2

array([ 20,  40,  60,  80, 100])

In [94]:
a=np.array([10,20,30,40,50])
a-2

array([ 8, 18, 28, 38, 48])

In [96]:
a=np.array([10,20,30,40,50])
a//2

array([ 5, 10, 15, 20, 25])

In [98]:
a=np.array([10,20,30,40,50])
a/2

array([ 5., 10., 15., 20., 25.])

In [100]:
a=np.array([10,20,30,40,50])
a**2

array([ 100,  400,  900, 1600, 2500])

In [102]:
a=np.array([10,20,30,40,50])
print(a%2)

[0 0 0 0 0]


In [104]:
a=np.array([[10,20,30],[40,50,60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [106]:
a+2

array([[12, 22, 32],
       [42, 52, 62]])

In [108]:
a**2

array([[ 100,  400,  900],
       [1600, 2500, 3600]])

In [110]:
a%3

array([[1, 2, 0],
       [1, 2, 0]])

In [112]:
a//2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [114]:
a//3

array([[ 3,  6, 10],
       [13, 16, 20]])

In [116]:
a//4

array([[ 2,  5,  7],
       [10, 12, 15]])

In [120]:
a**2

array([[ 100,  400,  900],
       [1600, 2500, 3600]])